$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay: true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    responsive:{
        300:{
            items:1
        },
        550:{
            items:2
        },
        800:{
            items:3
        },
        1000:{
            items:3
        }
    }
})